/**
 * One-time extraction: lifts the doctor roster out of the original frontend
 * service into the API config, so the seeded database matches the UI exactly.
 * Kept in the repo for provenance — re-runnable if the roster ever changes.
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const src = fs.readFileSync(path.join(root, "src/services/doctorService.ts"), "utf8");

const re =
  /name: "(Dr\.[^"]+)",\s*\n\s*qualification: "([^"]+)",\s*\n\s*specialty: "([^"]+)",\s*\n\s*department: "([^"]+)",\s*\n\s*opdTiming: "([^"]+)",[\s\S]*?initials: "([^"]+)",\s*\n\s*room: "([^"]+)"/g;

const toMin = (s) => {
  const mm = s.match(/(\d+):(\d+)\s*(AM|PM)/i);
  let h = Number(mm[1]) % 12;
  if (/pm/i.test(mm[3])) h += 12;
  return h * 60 + Number(mm[2]);
};

const byDept = {};
let m;
while ((m = re.exec(src))) {
  const [, name, qualification, specialty, department, opdTiming, , room] = m;
  const [a, b] = opdTiming.split("\u2013").map((s) => s.trim());
  (byDept[department] ||= []).push({
    name,
    qualification,
    specialty,
    room,
    opdStartMin: toMin(a),
    opdEndMin: toMin(b),
    slotMinutes: 5,
  });
}

const aliases = {
  General: "General Medicine",
  "General medicine": "General Medicine",
  Medicine: "General Medicine",
  Internal: "General Medicine",
  Paediatrics: "Paediatrics",
  Pediatrics: "Paediatrics",
  Child: "Paediatrics",
  Gynae: "Obstetrics & Gynaecology",
  Gynaecology: "Obstetrics & Gynaecology",
  "Obstetrics and Gynaecology": "Obstetrics & Gynaecology",
  Orthopaedics: "Orthopaedics",
  Orthopedics: "Orthopaedics",
  Surgery: "General Surgery",
  ENT: "ENT",
  Ophthalmology: "Ophthalmology",
  Dermatology: "Dermatology",
  Cardiology: "Cardiology",
  Neurology: "Neurology",
  Dental: "Dental",
};

const header = [
  "/**",
  " * Canonical OPD roster.",
  " *",
  " * Lifted verbatim from the original `src/services/doctorService.ts` so the",
  " * consultants patients already see are exactly the ones now persisted in the",
  " * database - the move to a real backend changed no name, room or timing.",
  " *",
  " * OPD windows are stored as minutes from midnight so the server can compute",
  ' * "open now" and slot capacity without parsing display strings.',
  " *",
  " * Generated by scripts/gen-roster.cjs",
  " */",
  "",
  "export type RosterDoctor = {",
  "  name: string;",
  "  qualification: string;",
  "  specialty: string;",
  "  room: string;",
  "  opdStartMin: number;",
  "  opdEndMin: number;",
  "  slotMinutes?: number;",
  "};",
  "",
  "/** OSM speciality tag -> our canonical department name. */",
  "export const SPECIALITY_ALIASES: Record<string, string> = " + JSON.stringify(aliases, null, 2) + ";",
  "",
  "export const STANDARD_DEPARTMENTS: string[] = " + JSON.stringify(Object.keys(byDept), null, 2) + ";",
  "",
  "export const DOCTOR_ROSTER: Record<string, RosterDoctor[]> = " + JSON.stringify(byDept, null, 2) + ";",
  "",
].join("\n");

fs.writeFileSync(path.join(root, "apps/api/src/config/roster.ts"), header);
console.log(
  "wrote roster.ts —",
  Object.values(byDept).flat().length,
  "doctors across",
  Object.keys(byDept).length,
  "departments"
);
